---
- name: omero server | check if the venv3 dir exists
  stat:
    path: "{{ omero_server_virtualenv_basedir }}/bin/python"
  register: venv_dir

- name: omero server | get output of the version cmd in present venv3
  become: true
  ansible.builtin.command: "{{ omero_server_virtualenv_basedir }}/bin/python --version"
  register: omero_server_venv_vers
  when: venv_dir.stat.exists
  changed_when: false

- name: omero server | stop the server
  become: true
  service:
    name: omero-server
    state: stopped
  when:
    - venv_dir.stat.exists
    - python3_virtualenv_version not in  omero_server_venv_vers.stdout

- name: omero server | delete the omero_server_virtualenv_basedir
  become: true
  ansible.builtin.command: |
    rm -rf {{ omero_server_virtualenv_basedir }}
  when:
    - venv_dir.stat.exists
    - python3_virtualenv_version not in  omero_server_venv_vers.stdout
