---
- src: ome.omero_common
- name: ome.basedeps
  src: https://github.com/pwalczysko/ansible-role-basedeps/
  version: fix-repo-rhel
- src: ome.java
- src: ome.python3_virtualenv
- src: ome.ice
- src: ome.postgresql_client
